package com.example.compilTest.core.parser;

/**
 * Created with IntelliJ IDEA.
 */
public enum Nonterminal {
    PROGRAM,
    A,
    FUNCTION_LIST,
    U_FUNCTION_LIST,
    V_FUNCTION_LIST,
    FUNCTION,
    FUNCTION_ARGUMENT,
    ARGUMENT_LIST,
    U_ARGUMENT_LIST,
    V_ARGUMENT_LIST,
    INSTRUCTION_LIST,
    U_INSTRUCTION_LIST,
    V_INSTRUCTION_LIST,
    FUNCTION_CALL,
    B,
    ARGUMENT_CALL_LIST,
    U_ARGUMENT_CALL_LIST,
    V_ARGUMENT_CALL_LIST,
    INSTRUCTION,
    CONDITION,
    CONDITION_END,
    SIMPLE_EXPRESSION,
    EXPRESSION, U_P_EXPRESSION, V_P_EXPRESSION, O_EXPRESSION, U_Q_EXPRESSION, V_Q_EXPRESSION, U_R_EXPRESSION, V_R_EXPRESSION, U_S_EXPRESSION, V_S_EXPRESSION, U_T_EXPRESSION, V_T_EXPRESSION, U_U_EXPRESSION, V_U_EXPRESSION, X_EXPRESSION;

    public static Nonterminal getStartSymbol(){
        return PROGRAM;
    }
}
